/* Generated by AN DISI Unibo */ 
package it.unibo.tempdetector;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Tempdetector extends QActorMsgQueue{
	public MsgHandle_Tempdetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
