/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qarescuer;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.is.interfaces.protocols.IConnInteraction;
import it.unibo.qactors.QActorContext;

public class Qarescuer extends AbstractQarescuer { 
	public Qarescuer(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	
	private IConnInteraction connection = null;
	
	public void initConnectionWithAndroid(String actorName, String hostname, int port) {
		this.connection = CommsWithOutside.initConnection(actorName, hostname, port);
	}
	
	public void sendMessageToAndroid(String message) {
		try {
			CommsWithOutside.sendMsg(this.connection, message);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
