/* Generated by AN DISI Unibo */ 
package it.unibo.evlogagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Evlogagent extends QActorMsgQueue{
	public MsgHandle_Evlogagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
