/* Generated by AN DISI Unibo */ 
package it.unibo.qabuttonthing;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabuttonthing extends QActorMsgQueue{
	public MsgHandle_Qabuttonthing(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
