/* Generated by AN DISI Unibo */ 
package it.unibo.player0;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractPlayer0 extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractPlayer0(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/player0/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/player0/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitCommand",waitCommand);
	    	stateTab.put("waitforMsg",waitforMsg);
	    	stateTab.put("starts",starts);
	    	stateTab.put("end",end);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "player0 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"ROBOT starts...\"";
	    	println( temporaryStr );  
	    	//switchTo waitCommand
	        switchToPlanAsNextState(pr, myselfName, "player0_"+myselfName, 
	              "waitCommand",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitCommand = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitCommand",-1);
	    	String myselfName = "waitCommand";  
	    	//bbb
	     msgTransition( pr,myselfName,"player0_"+myselfName,false,
	          new StateFun[]{stateTab.get("waitforMsg") }, 
	          new String[]{"true","M","consoleCmdMsg" },
	          60000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitCommand){  
	    	 println( getName() + " plan=waitCommand WARNING:" + e_waitCommand.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitCommand
	    
	    StateFun waitforMsg = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitforMsg",-1);
	    	String myselfName = "waitforMsg";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("consoleCmd(start)");
	    	if( currentMessage != null && currentMessage.msgId().equals("consoleCmdMsg") && 
	    		pengine.unify(curT, Term.createTerm("consoleCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = "\"ROBOT received START\"";
	    		println( temporaryStr );  
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"start(X)","start(x)", guardVars ).toString();
	    		sendMsg("startMsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    		};//actionseq
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("consoleCmd(halt)");
	    	if( currentMessage != null && currentMessage.msgId().equals("consoleCmdMsg") && 
	    		pengine.unify(curT, Term.createTerm("consoleCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		//println("WARNING: variable substitution not yet fully implemented " ); 
	    		{//actionseq
	    		temporaryStr = "\"ROBOT received STOP\"";
	    		println( temporaryStr );  
	    		temporaryStr = QActorUtils.unifyMsgContent(pengine,"halt(X)","halt(x)", guardVars ).toString();
	    		sendMsg("stopMsg",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    		};//actionseq
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"player0_"+myselfName,false,
	          new StateFun[]{stateTab.get("starts"), stateTab.get("end") }, 
	          new String[]{"true","M","startMsg", "true","M","stopMsg" },
	          60000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitforMsg){  
	    	 println( getName() + " plan=waitforMsg WARNING:" + e_waitforMsg.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitforMsg
	    
	    StateFun starts = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("starts",-1);
	    	String myselfName = "starts";  
	    	temporaryStr = "\"ROBOT execution started\"";
	    	println( temporaryStr );  
	    	//switchTo waitCommand
	        switchToPlanAsNextState(pr, myselfName, "player0_"+myselfName, 
	              "waitCommand",false, true, null); 
	    }catch(Exception e_starts){  
	    	 println( getName() + " plan=starts WARNING:" + e_starts.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//starts
	    
	    StateFun end = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("end",-1);
	    	String myselfName = "end";  
	    	temporaryStr = "\"ROBOT ends due to STOP message\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(4000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "end";
	    	if( ! aar.getGoon() ) return ;
	    	repeatPlanNoTransition(pr,myselfName,"player0_"+myselfName,false,false);
	    }catch(Exception e_end){  
	    	 println( getName() + " plan=end WARNING:" + e_end.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//end
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
