/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRealRobotWithLedExecutor;
import alice.tuprolog.Term;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.qactors.platform.EventHandlerComponent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorUtils;

public abstract class AbstractEvh1 extends EventHandlerComponent { 
protected IEventItem event;
	public AbstractEvh1(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, eventIds, outEnvView);
  	}
	@Override
	public void doJob() throws Exception {	}
	
	public void handleCurrentEvent() throws Exception {
		event = this.currentEvent; //AKKA getEventItem();
		if( event == null ) return;
//showMsg( "---------------------------------------------------------------------" );	
showMsg( event.getPrologRep()  );				 
//showMsg( "---------------------------------------------------------------------" );	
		QActorUtils.sendMsgExecInternal("mbotled_ctrl","memoCurrentEvent("+event.getPrologRep()+",true)");
		//QActorUtils.getQActor("mbotled_ctrl").memoCurrentEvent( event, true);
		QActorUtils.sendMsgExecInternal("mbotled_ctrl","ledHandle");
		//QActorUtils.solveGoal(QActorUtils.getQActor("mbotled_ctrl").getPrologEngine(),"ledHandle");
	}//handleCurrentEvent
	
	@Override
	protected void handleQActorEvent(IEventItem ev) {
		super.handleQActorEvent(ev);
 		try {
			handleCurrentEvent();
		} catch (Exception e) {
 			e.printStackTrace();
		}
	}//handleQActorEvent
	
}
