/* Generated by AN DISI Unibo */ 
package it.unibo.control;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractControl extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractControl(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/control/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/control/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForFirstClick",waitForFirstClick);
	    	stateTab.put("doBlink",doBlink);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "control tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	//switchTo waitForFirstClick
	        switchToPlanAsNextState(pr, myselfName, "control_"+myselfName, 
	              "waitForFirstClick",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForFirstClick = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForFirstClick",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForFirstClick";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmdToLed(CMD)","cmdToLed(turnOff)", guardVars ).toString();
	    	sendMsg("cmdToLed","ledmodel", QActorContext.dispatch, temporaryStr ); 
	    	//bbb
	     msgTransition( pr,myselfName,"control_"+myselfName,false,
	          new StateFun[]{stateTab.get("doBlink") }, 
	          new String[]{"true","E","local_click" },
	          100000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForFirstClick){  
	    	 println( getName() + " plan=waitForFirstClick WARNING:" + e_waitForFirstClick.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForFirstClick
	    
	    StateFun doBlink = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doBlink",-1);
	    	String myselfName = "doBlink";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmdToLed(CMD)","cmdToLed(turnOn)", guardVars ).toString();
	    	sendMsg("cmdToLed","ledmodel", QActorContext.dispatch, temporaryStr ); 
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(300,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "doBlink";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"cmdToLed(CMD)","cmdToLed(turnOff)", guardVars ).toString();
	    	sendMsg("cmdToLed","ledmodel", QActorContext.dispatch, temporaryStr ); 
	    	//bbb
	     msgTransition( pr,myselfName,"control_"+myselfName,false,
	          new StateFun[]{stateTab.get("waitForFirstClick") }, 
	          new String[]{"true","E","local_click" },
	          300, "doBlink" );//msgTransition
	    }catch(Exception e_doBlink){  
	    	 println( getName() + " plan=doBlink WARNING:" + e_doBlink.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doBlink
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
