/* Generated by AN DISI Unibo */ 
package it.unibo.polarlogagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Polarlogagent extends QActorMsgQueue{
	public MsgHandle_Polarlogagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
