/* Generated by AN DISI Unibo */ 
package it.unibo.ledmockgui;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledmockgui extends QActorMsgQueue{
	public MsgHandle_Ledmockgui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
