/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.applr0agent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Applr0agent extends AbstractApplr0agent { 
	public Applr0agent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
