/* Generated by AN DISI Unibo */ 
package it.unibo.sonardetector;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSonardetector extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	//protected String mqttServer = "";
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSonardetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/sonardetector/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/sonardetector/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForEvents",waitForEvents);
	    	stateTab.put("sendToRadar",sendToRadar);
	    	stateTab.put("handleRealSonar",handleRealSonar);
	    	stateTab.put("showObstcle",showObstcle);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "sonardetector tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"sonardetector STARTS \"";
	    	println( temporaryStr );  
	    	//switchTo waitForEvents
	        switchToPlanAsNextState(pr, myselfName, "sonardetector_"+myselfName, 
	              "waitForEvents",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForEvents = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForEvents",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForEvents";  
	    	//bbb
	     msgTransition( pr,myselfName,"sonardetector_"+myselfName,false,
	          new StateFun[]{stateTab.get("sendToRadar"), stateTab.get("showObstcle"), stateTab.get("handleRealSonar") }, 
	          new String[]{"true","E","sonar", "true","E","sonarDetect", "true","E","realSonar" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForEvents){  
	    	 println( getName() + " plan=waitForEvents WARNING:" + e_waitForEvents.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForEvents
	    
	    StateFun sendToRadar = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("sendToRadar",-1);
	    	String myselfName = "sendToRadar";  
	    	printCurrentEvent(false);
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(sonar1,TARGET,DISTANCE)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sonar") && 
	    		pengine.unify(curT, Term.createTerm("sonar(SONAR,TARGET,DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="p(DISTANCE,30)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("sonar(SONAR,TARGET,DISTANCE)"),  Term.createTerm("sonar(sonar1,TARGET,DISTANCE)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "polar", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(sonar1,TARGET,DISTANCE)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sonar") && 
	    		pengine.unify(curT, Term.createTerm("sonar(SONAR,TARGET,DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="sonar(sonar1,TARGET,DISTANCE)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("sonar(SONAR,TARGET,DISTANCE)"),  Term.createTerm("sonar(sonar1,TARGET,DISTANCE)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "sonar", parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(sonar2,TARGET,DISTANCE)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sonar") && 
	    		pengine.unify(curT, Term.createTerm("sonar(SONAR,TARGET,DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="p(DISTANCE,120)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("sonar(SONAR,TARGET,DISTANCE)"),  Term.createTerm("sonar(sonar2,TARGET,DISTANCE)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "polar", parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"sonardetector_"+myselfName,false,true);
	    }catch(Exception e_sendToRadar){  
	    	 println( getName() + " plan=sendToRadar WARNING:" + e_sendToRadar.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//sendToRadar
	    
	    StateFun handleRealSonar = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleRealSonar",-1);
	    	String myselfName = "handleRealSonar";  
	    	printCurrentEvent(false);
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sonar(DISTANCE)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("realSonar") && 
	    		pengine.unify(curT, Term.createTerm("sonar(DISTANCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="p(DISTANCE,0)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("sonar(DISTANCE)"),  Term.createTerm("sonar(DISTANCE)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "polar", parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"sonardetector_"+myselfName,false,true);
	    }catch(Exception e_handleRealSonar){  
	    	 println( getName() + " plan=handleRealSonar WARNING:" + e_handleRealSonar.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleRealSonar
	    
	    StateFun showObstcle = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("showObstcle",-1);
	    	String myselfName = "showObstcle";  
	    	temporaryStr = "\"found obstacle\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "p(Distance,Angle)","p(30,90)", guardVars ).toString();
	    	emit( "polar", temporaryStr );
	    	repeatPlanNoTransition(pr,myselfName,"sonardetector_"+myselfName,false,true);
	    }catch(Exception e_showObstcle){  
	    	 println( getName() + " plan=showObstcle WARNING:" + e_showObstcle.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//showObstcle
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
