/* Generated by AN DISI Unibo */ 
package it.unibo.bls1mCtx;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainBls1mCtx  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"bls1mctx", "./srcMore/it/unibo/bls1mCtx/bls1m.pl", 
		"./srcMore/it/unibo/bls1mCtx/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
