/* Generated by AN DISI Unibo */ 
package it.unibo.tofronted;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Tofronted extends QActorMsgQueue{
	public MsgHandle_Tofronted(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
