/* Generated by AN DISI Unibo */ 
package it.unibo.mbotusercmdmanager;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mbotusercmdmanager extends QActorMsgQueue{
	public MsgHandle_Mbotusercmdmanager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
