/* Generated by AN DISI Unibo */ 
package it.unibo.qacoapanotherobserver;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacoapanotherobserver extends QActorMsgQueue{
	public MsgHandle_Qacoapanotherobserver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
