/* Generated by AN DISI Unibo */ 
package it.unibo.btuuonmockgui;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Btuuonmockgui extends QActorMsgQueue{
	public MsgHandle_Btuuonmockgui(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
