/* Generated by AN DISI Unibo */ 
package it.unibo.rescuerContext;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainRescuerContext  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"rescuercontext", "./srcMore/it/unibo/rescuerContext/rescuer.pl", 
		"./srcMore/it/unibo/rescuerContext/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
