/* Generated by AN DISI Unibo */ 
package it.unibo.blsMvcCtx;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainBlsMvcCtx  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/blsMvcCtx";
	return QActorContext.initQActorSystem(
		"blsmvcctx", "./srcMore/it/unibo/blsMvcCtx/blsmvc.pl", 
		"./srcMore/it/unibo/blsMvcCtx/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
