/* Generated by AN DISI Unibo */ 
package it.unibo.ctxQaBlsThingsMqtt;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxQaBlsThingsMqtt  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxqablsthingsmqtt", "./srcMore/it/unibo/ctxQaBlsThingsMqtt/qablsthingsmqtt.pl", 
		"./srcMore/it/unibo/ctxQaBlsThingsMqtt/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
