/* Generated by AN DISI Unibo */ 
package it.unibo.qacoapoberver;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacoapoberver extends QActorMsgQueue{
	public MsgHandle_Qacoapoberver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
