/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.ledmqtt;
import it.unibo.bls.highLevel.interfaces.IDevLed.LedColor;
import it.unibo.bls.raspberry.components.DeviceLedPi4j;
import it.unibo.buttonLed.components.DeviceLedImpl;
import it.unibo.buttonLedSystem.gui.components.DeviceLedGui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Ledmqtt extends AbstractLedmqtt { 
 	private DeviceLedImpl ledlowlevel;
	
	public Ledmqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
	public void createLedGui(){
		try {
			ledlowlevel = new DeviceLedGui("led", outEnvView, LedColor.GREEN);
 		} catch (Exception e) {
 			e.printStackTrace();
		}
   	}	
	
	public void createPi4jLed(int pinNum ){
		try {
			println("Led createPi4jLed STARTS "   + pinNum   );
			ledlowlevel = new DeviceLedPi4j("led0",  outEnvView, LedColor.GREEN, pinNum );
 			println("Led createPi4jLed ENDS "   );
		} catch (Exception e) {
			println("ERROR " + e.getMessage() );
		}
	}
	
	public void ledSwitch(){
		ledlowlevel.doSwitch();
 	}
	
 }
