/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.tempdetector1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Tempdetector1 extends AbstractTempdetector1 { 
	public Tempdetector1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
