/* Generated by AN DISI Unibo */ 
package it.unibo.mvccontroller1;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mvccontroller1 extends QActorMsgQueue{
	public MsgHandle_Mvccontroller1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
