/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRobotInWenv;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evobstacle extends AbstractEvobstacle { 
	public Evobstacle(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
