/* Generated by AN DISI Unibo */ 
package it.unibo.bls2Ctx;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainBls2Ctx  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"bls2ctx", "./srcMore/it/unibo/bls2Ctx/bls2.pl", 
		"./srcMore/it/unibo/bls2Ctx/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
