/* Generated by AN DISI Unibo */ 
package it.unibo.webguiclient;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Webguiclient extends QActorMsgQueue{
	public MsgHandle_Webguiclient(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
