/* Generated by AN DISI Unibo */ 
package it.unibo.qablslogic;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qablslogic extends QActorMsgQueue{
	public MsgHandle_Qablslogic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
