/* Generated by AN DISI Unibo */ 
package it.unibo.pressphysicalsimulator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Pressphysicalsimulator extends QActorMsgQueue{
	public MsgHandle_Pressphysicalsimulator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
