/* Generated by AN DISI Unibo */ 
package it.unibo.mbotmanager;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractMbotmanager extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractMbotmanager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/mbotmanager/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/mbotmanager/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitRequest",waitRequest);
	    	stateTab.put("checkDeadine",checkDeadine);
	    	stateTab.put("handleBookingRequest",handleBookingRequest);
	    	stateTab.put("handelGetRobotDriveInterface",handelGetRobotDriveInterface);
	    	stateTab.put("handleBookingRelease",handleBookingRelease);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "mbotmanager tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	parg = "initResourceState";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " ??goalResult(initResourceState)" )) != null ){
	    	temporaryStr = "\"mbotmanager STARTS\"";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?getVal(tokenVal,V)" )) != null ){
	    	temporaryStr = "curTokenValue(V)";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	//switchTo waitRequest
	        switchToPlanAsNextState(pr, myselfName, "mbotmanager_"+myselfName, 
	              "waitRequest",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitRequest",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitRequest";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " not !?isengaged(TOKEN)" )) != null )
	    	{
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "notify(ARG)","notify(available)", guardVars ).toString();
	    	emit( "notify", temporaryStr );
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?isengaged(TOKEN)" )) != null ){
	    	temporaryStr = "mbotmanager(WAITS,isengaged(TOKEN))";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	else{ temporaryStr = "mbotmanager(WAITS,free)";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"mbotmanager_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleBookingRequest"), stateTab.get("handelGetRobotDriveInterface"), stateTab.get("handleBookingRelease") }, 
	          new String[]{"true","M","bookingRequest", "true","M","getRobotDriveInterface", "true","M","bookingRelease" },
	          10000, "checkDeadine" );//msgTransition
	    }catch(Exception e_waitRequest){  
	    	 println( getName() + " plan=waitRequest WARNING:" + e_waitRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitRequest
	    
	    StateFun checkDeadine = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("checkDeadine",-1);
	    	String myselfName = "checkDeadine";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?isengaged(TOKEN)" )) != null ){
	    	temporaryStr = "\"acquisition-deadline EXPIRED\"";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?isengaged(TOKEN)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"bookingRelease(ACCESSTOKEN)","bookingRelease(TOKEN)", guardVars ).toString();
	    	sendMsg("bookingRelease",getNameNoCtrl(), QActorContext.dispatch, temporaryStr ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"mbotmanager_"+myselfName,false,true);
	    }catch(Exception e_checkDeadine){  
	    	 println( getName() + " plan=checkDeadine WARNING:" + e_checkDeadine.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//checkDeadine
	    
	    StateFun handleBookingRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleBookingRequest",-1);
	    	String myselfName = "handleBookingRequest";  
	    	temporaryStr = "\"handleBookingRequest STARTS\"";
	    	println( temporaryStr );  
	    	printCurrentMessage(false);
	    	parg = "engage(RES)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " ??goalResult(engage(RES))" )) != null ){
	    	temporaryStr = "bookingRequestAnswer(RES)";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr );
	    	replyToCaller("bookingRequestAnswer", temporaryStr);
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"mbotmanager_"+myselfName,false,true);
	    }catch(Exception e_handleBookingRequest){  
	    	 println( getName() + " plan=handleBookingRequest WARNING:" + e_handleBookingRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleBookingRequest
	    
	    StateFun handelGetRobotDriveInterface = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handelGetRobotDriveInterface",-1);
	    	String myselfName = "handelGetRobotDriveInterface";  
	    	temporaryStr = "\"handelGetRobotDriveInterface STARTS\"";
	    	println( temporaryStr );  
	    	printCurrentMessage(false);
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("getRobotDriveInterface(TOKEN)");
	    	if( currentMessage != null && currentMessage.msgId().equals("getRobotDriveInterface") && 
	    		pengine.unify(curT, Term.createTerm("getRobotDriveInterface(ACCESSTOKEN)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="checkToken(TOKEN)";
	    		/* PHead */
	    		parg =  updateVars( Term.createTerm("getRobotDriveInterface(ACCESSTOKEN)"), 
	    		                    Term.createTerm("getRobotDriveInterface(TOKEN)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    			if( parg != null ) {
	    			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,86400000);
	    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "handelGetRobotDriveInterface";
	    					if( aar.getTimeRemained() <= 0 ) addRule("tout(demo,"+getName()+")");
	    					if( ! aar.getGoon() ) return ;
	    				} 			
	    				if( aar.getResult().equals("failure")){
	    					if( ! aar.getGoon() ) return ;
	    				}else if( ! aar.getGoon() ) return ;
	    			}
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " ??goalResult(checkToken(TOKEN))" )) != null ){
	    	temporaryStr = "\"TODO RobotDriveInterfaceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee\"";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"mbotmanager_"+myselfName,false,true);
	    }catch(Exception e_handelGetRobotDriveInterface){  
	    	 println( getName() + " plan=handelGetRobotDriveInterface WARNING:" + e_handelGetRobotDriveInterface.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handelGetRobotDriveInterface
	    
	    StateFun handleBookingRelease = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleBookingRelease",-1);
	    	String myselfName = "handleBookingRelease";  
	    	temporaryStr = "\"handleBookingRelease emitting notify\"";
	    	println( temporaryStr );  
	    	parg = "disengage";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "notify(ARG)","notify(available)", guardVars ).toString();
	    	emit( "notify", temporaryStr );
	    	//switchTo waitRequest
	        switchToPlanAsNextState(pr, myselfName, "mbotmanager_"+myselfName, 
	              "waitRequest",false, false, null); 
	    }catch(Exception e_handleBookingRelease){  
	    	 println( getName() + " plan=handleBookingRelease WARNING:" + e_handleBookingRelease.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleBookingRelease
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
