/* Generated by AN DISI Unibo */ 
package it.unibo.mbotmanager;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mbotmanager extends QActorMsgQueue{
	public MsgHandle_Mbotmanager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
