/* Generated by AN DISI Unibo */ 
package it.unibo.ctxApplR0;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evhtask extends AbstractEvhtask { 
	public Evhtask(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
