/* Generated by AN DISI Unibo */ 
package it.unibo.frontendmanager1;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractFrontendmanager1 extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractFrontendmanager1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/frontendmanager1/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/frontendmanager1/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("userLogin",userLogin);
	    	stateTab.put("userGui",userGui);
	    	stateTab.put("sendStart",sendStart);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "frontendmanager1 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"FRONTEND starts...\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	//switchTo userLogin
	        switchToPlanAsNextState(pr, myselfName, "frontendmanager1_"+myselfName, 
	              "userLogin",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun userLogin = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("userLogin",-1);
	    	String myselfName = "userLogin";  
	    	temporaryStr = "\"FRONTEND login page\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "userLogin";
	    	if( ! aar.getGoon() ) return ;
	    	//switchTo userGui
	        switchToPlanAsNextState(pr, myselfName, "frontendmanager1_"+myselfName, 
	              "userGui",false, false, null); 
	    }catch(Exception e_userLogin){  
	    	 println( getName() + " plan=userLogin WARNING:" + e_userLogin.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//userLogin
	    
	    StateFun userGui = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("userGui",-1);
	    	String myselfName = "userGui";  
	    	temporaryStr = "\"FRONTEND gui page\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "userGui";
	    	if( ! aar.getGoon() ) return ;
	    	//switchTo sendStart
	        switchToPlanAsNextState(pr, myselfName, "frontendmanager1_"+myselfName, 
	              "sendStart",false, false, null); 
	    }catch(Exception e_userGui){  
	    	 println( getName() + " plan=userGui WARNING:" + e_userGui.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//userGui
	    
	    StateFun sendStart = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("sendStart",-1);
	    	String myselfName = "sendStart";  
	    	temporaryStr = "\"FRONTEND send start\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"frontendCmd(X)","frontendCmd(x)", guardVars ).toString();
	    	sendExtMsg("frontendCmdMsg","mvccontroller1", "ctxConsole", QActorContext.dispatch, temporaryStr ); 
	    	repeatPlanNoTransition(pr,myselfName,"frontendmanager1_"+myselfName,false,false);
	    }catch(Exception e_sendStart){  
	    	 println( getName() + " plan=sendStart WARNING:" + e_sendStart.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//sendStart
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
