/* Generated by AN DISI Unibo */ 
package it.unibo.ctMindOfRobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtMindOfRobot  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctmindofrobot", "./srcMore/it/unibo/ctMindOfRobot/mindofrobot.pl", 
		"./srcMore/it/unibo/ctMindOfRobot/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
