/* Generated by AN DISI Unibo */ 
package it.unibo.testeruser1;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
import it.unibo.baseEnv.basicFrame.EnvFrame;
import alice.tuprolog.SolveInfo;
import it.unibo.is.interfaces.IActivity;
import it.unibo.is.interfaces.IIntent;
public abstract class AbstractTesteruser1 extends QActor implements IActivity{ 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			EnvFrame env = new EnvFrame( "Env_testeruser1", java.awt.Color.cyan  , java.awt.Color.black );
			env.init();
			env.setSize(800,430); 
			IOutputEnvView newOutEnvView = ((EnvFrame) env).getOutputEnvView();
			return newOutEnvView;
		}
		public AbstractTesteruser1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/testeruser1/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			addInputPanel(80);
			addCmdPanels();
			this.planFilePath = "./srcMore/it/unibo/testeruser1/plans.txt";
	  	}
	protected void addInputPanel(int size){
		((EnvFrame) env).addInputPanel(size);			
	}
	protected void addCmdPanels(){
		((EnvFrame) env).addCmdPanel("input", new String[]{"INPUT"}, this);
		((EnvFrame) env).addCmdPanel("alarm", new String[]{"FIRE"}, this);
		((EnvFrame) env).addCmdPanel("help",  new String[]{"HELP"}, this);				
	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doRequest",doRequest);
	    	stateTab.put("handleAnswer",handleAnswer);
	    	stateTab.put("nextStep",nextStep);
	    	stateTab.put("usage",usage);
	    	stateTab.put("release",release);
	    	stateTab.put("waitForNotification",waitForNotification);
	    	stateTab.put("lookAtNotification",lookAtNotification);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "testeruser1 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	parg = "getName"; 
	    	actorOpExecute(parg, false);	//OCT17		 
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " ??actorOpDone(OP,R)" )) != null ){
	    	temporaryStr = "myname(R)";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	//switchTo doRequest
	        switchToPlanAsNextState(pr, myselfName, "testeruser1_"+myselfName, 
	              "doRequest",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doRequest",-1);
	    	String myselfName = "doRequest";  
	    	temporaryStr = "\"testerUser1 emits request\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"bookingRequest(NOTIFYME)","bookingRequest(true)", guardVars ).toString();
	    	sendExtMsg("bookingRequest","mbotmanager", "ctxMbotManager", QActorContext.dispatch, temporaryStr ); 
	    	//bbb
	     msgTransition( pr,myselfName,"testeruser1_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleAnswer") }, 
	          new String[]{"true","M","bookingRequestAnswer" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_doRequest){  
	    	 println( getName() + " plan=doRequest WARNING:" + e_doRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doRequest
	    
	    StateFun handleAnswer = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleAnswer",-1);
	    	String myselfName = "handleAnswer";  
	    	temporaryStr = "\"testerUser1 handleAnswer\"";
	    	println( temporaryStr );  
	    	printCurrentMessage(false);
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("bookingRequestAnswer(failure)");
	    	if( currentMessage != null && currentMessage.msgId().equals("bookingRequestAnswer") && 
	    		pengine.unify(curT, Term.createTerm("bookingRequestAnswer(TOKEN)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="failure(notoken)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("bookingRequestAnswer(TOKEN)"),  Term.createTerm("bookingRequestAnswer(failure)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("failure",getNameNoCtrl(), QActorContext.dispatch, parg ); 
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("bookingRequestAnswer(token(TK))");
	    	if( currentMessage != null && currentMessage.msgId().equals("bookingRequestAnswer") && 
	    		pengine.unify(curT, Term.createTerm("bookingRequestAnswer(TOKEN)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="usage(token(TK))";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("bookingRequestAnswer(TOKEN)"),  Term.createTerm("bookingRequestAnswer(token(TK))"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("usage",getNameNoCtrl(), QActorContext.dispatch, parg ); 
	    	}
	    	//switchTo nextStep
	        switchToPlanAsNextState(pr, myselfName, "testeruser1_"+myselfName, 
	              "nextStep",false, false, null); 
	    }catch(Exception e_handleAnswer){  
	    	 println( getName() + " plan=handleAnswer WARNING:" + e_handleAnswer.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleAnswer
	    
	    StateFun nextStep = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("nextStep",-1);
	    	String myselfName = "nextStep";  
	    	temporaryStr = "\"testerUser1 nextStep\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"testeruser1_"+myselfName,false,
	          new StateFun[]{stateTab.get("usage"), stateTab.get("waitForNotification"), stateTab.get("init") }, 
	          new String[]{"true","M","usage", "true","M","failure", "true","M","tryagain" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_nextStep){  
	    	 println( getName() + " plan=nextStep WARNING:" + e_nextStep.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//nextStep
	    
	    StateFun usage = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("usage",-1);
	    	String myselfName = "usage";  
	    	temporaryStr = "\"testerUser1 usage\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usage(token(TK))");
	    	if( currentMessage != null && currentMessage.msgId().equals("usage") && 
	    		pengine.unify(curT, Term.createTerm("usage(TOKEN)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="token(TK)";
	    		/* AddRule */
	    		parg = updateVars(Term.createTerm("usage(TOKEN)"),  Term.createTerm("usage(token(TK))"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) addRule(parg);	    		  					
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?token(TOKEN)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"getRobotDriveInterface(ACCESSTOKEN)","getRobotDriveInterface(TOKEN)", guardVars ).toString();
	    	sendExtMsg("getRobotDriveInterface","mbotmanager", "ctxMbotManager", QActorContext.dispatch, temporaryStr ); 
	    	}
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(4000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "usage";
	    	if( ! aar.getGoon() ) return ;
	    	//switchTo release
	        switchToPlanAsNextState(pr, myselfName, "testeruser1_"+myselfName, 
	              "release",false, false, null); 
	    }catch(Exception e_usage){  
	    	 println( getName() + " plan=usage WARNING:" + e_usage.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//usage
	    
	    StateFun release = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("release",-1);
	    	String myselfName = "release";  
	    	temporaryStr = "\"testerUser1 release\"";
	    	println( temporaryStr );  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " ??token(TOKEN)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"bookingRelease(ACCESSTOKEN)","bookingRelease(TOKEN)", guardVars ).toString();
	    	sendExtMsg("bookingRelease","mbotmanager", "ctxMbotManager", QActorContext.dispatch, temporaryStr ); 
	    	}
	    	temporaryStr = "\"testerUser1 ENDS\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(6000000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "release";
	    	if( ! aar.getGoon() ) return ;
	    	repeatPlanNoTransition(pr,myselfName,"testeruser1_"+myselfName,false,false);
	    }catch(Exception e_release){  
	    	 println( getName() + " plan=release WARNING:" + e_release.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//release
	    
	    StateFun waitForNotification = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitForNotification",-1);
	    	String myselfName = "waitForNotification";  
	    	temporaryStr = "\"testerUser1 waitForNotification\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"testeruser1_"+myselfName,false,
	          new StateFun[]{stateTab.get("lookAtNotification") }, 
	          new String[]{"true","E","notify" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForNotification){  
	    	 println( getName() + " plan=waitForNotification WARNING:" + e_waitForNotification.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForNotification
	    
	    StateFun lookAtNotification = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("lookAtNotification",-1);
	    	String myselfName = "lookAtNotification";  
	    	temporaryStr = "\"testerUser1 lookAtNotification\"";
	    	println( temporaryStr );  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("notify(available)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("notify") && 
	    		pengine.unify(curT, Term.createTerm("notify(ARG)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="tryagain(true)";
	    			/* SendDispatch */
	    			parg = updateVars(Term.createTerm("notify(ARG)"),  Term.createTerm("notify(available)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) sendMsg("tryagain",getNameNoCtrl(), QActorContext.dispatch, parg ); 
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("notify(removed)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("notify") && 
	    		pengine.unify(curT, Term.createTerm("notify(ARG)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="endOfJob";
	    			/* AddRule */
	    			parg = updateVars(Term.createTerm("notify(ARG)"),  Term.createTerm("notify(removed)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) addRule(parg);	    		  					
	    	}
	    	//switchTo nextStep
	        switchToPlanAsNextState(pr, myselfName, "testeruser1_"+myselfName, 
	              "nextStep",false, false, " not !?endOfJob" 
	              ); 
	    }catch(Exception e_lookAtNotification){  
	    	 println( getName() + " plan=lookAtNotification WARNING:" + e_lookAtNotification.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//lookAtNotification
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
		/* 
		* ------------------------------------------------------------
		* IACTIVITY (aactor with GUI)
		* ------------------------------------------------------------
		*/
		private String[] actions = new String[]{
		    	"println( STRING | TERM )", 
		    	"play('./audio/music_interlude20.wav'),20000,'alarm,obstacle', 'handleAlarm,handleObstacle'",
		"emit(EVID,EVCONTENT)  ",
		"move(MOVE,DURATION,ANGLE)  with MOVE=mf|mb|ml|mr|ms",
		"forward( DEST, MSGID, MSGCONTENTTERM)"
		    };
		    protected void doHelp(){
				println("  GOAL ");
				println("[ GUARD ], ACTION  ");
				println("[ GUARD ], ACTION, DURATION ");
				println("[ GUARD ], ACTION, DURATION, ENDEVENT");
				println("[ GUARD ], ACTION, DURATION, EVENTS, PLANS");
				println("Actions:");
				for( int i=0; i<actions.length; i++){
					println(" " + actions[i] );
				}
		    }
		@Override
		public void execAction(String cmd) {
			if( cmd.equals("HELP") ){
				doHelp();
				return;
			}
			if( cmd.equals("FIRE") ){
				emit("alarm", "alarm(fire)");
				return;
			}
			String input = env.readln();
			//input = "\""+input+"\"";
			input = it.unibo.qactors.web.GuiUiKb.buildCorrectPrologString(input);
			//println("input=" + input);
			try {
				Term.createTerm(input);
	 			String eventMsg=it.unibo.qactors.web.QActorHttpServer.inputToEventMsg(input);
				//println("QActor eventMsg " + eventMsg);
				emit("local_"+it.unibo.qactors.web.GuiUiKb.inputCmd, eventMsg);
	  		} catch (Exception e) {
		 		println("QActor input error " + e.getMessage());
			}
		}
	 	
		@Override
		public void execAction() {}
		@Override
		public void execAction(IIntent input) {}
		@Override
		public String execActionWithAnswer(String cmd) {return null;}
	}
