/* Generated by AN DISI Unibo */ 
package it.unibo.frontendmanager;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Frontendmanager extends QActorMsgQueue{
	public MsgHandle_Frontendmanager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
