/* Generated by AN DISI Unibo */ 
package it.unibo.qabuttonthingmqtt;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabuttonthingmqtt extends QActorMsgQueue{
	public MsgHandle_Qabuttonthingmqtt(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
