/* Generated by AN DISI Unibo */ 
package it.unibo.mindtobody;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Mindtobody extends QActorMsgQueue{
	public MsgHandle_Mindtobody(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
