/* Generated by AN DISI Unibo */ 
package it.unibo.operatorconsole;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Operatorconsole extends QActorMsgQueue{
	public MsgHandle_Operatorconsole(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
