/* Generated by AN DISI Unibo */ 
package it.unibo.ctxTesterUser2;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxTesterUser2  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxtesteruser2", "./srcMore/it/unibo/ctxTesterUser2/testeruser2.pl", 
		"./srcMore/it/unibo/ctxTesterUser2/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
