/* Generated by AN DISI Unibo */ 
package it.unibo.worldobserver;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Worldobserver extends QActorMsgQueue{
	public MsgHandle_Worldobserver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
