/* Generated by AN DISI Unibo */ 
package it.unibo.blsMvcCtx;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evadapter extends AbstractEvadapter { 
	public Evadapter(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
