/* Generated by AN DISI Unibo */ 
package it.unibo.sonarguidetector;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sonarguidetector extends QActorMsgQueue{
	public MsgHandle_Sonarguidetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
