/* Generated by AN DISI Unibo */ 
package it.unibo.ledarduino;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledarduino extends QActorMsgQueue{
	public MsgHandle_Ledarduino(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
