/* Generated by AN DISI Unibo */ 
package it.unibo.ctxVirtualRobotExecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxVirtualRobotExecutor  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	it.unibo.is.interfaces.IBasicEnvAwt env=new it.unibo.baseEnv.basicFrame.EnvFrame( 
		"Env_ctxVirtualRobotExecutor",java.awt.Color.cyan , java.awt.Color.black );
	env.init();
	outEnvView = env.getOutputEnvView();
	String webDir = "./srcMore/it/unibo/ctxVirtualRobotExecutor";
	return QActorContext.initQActorSystem(
		"ctxvirtualrobotexecutor", "./srcMore/it/unibo/ctxVirtualRobotExecutor/virtualrobotexecutor.pl", 
		"./srcMore/it/unibo/ctxVirtualRobotExecutor/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
