/* Generated by AN DISI Unibo */ 
package it.unibo.ctxWebGuiExecutor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxWebGuiExecutor  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxWebGuiExecutor";
	return QActorContext.initQActorSystem(
		"ctxwebguiexecutor", "./srcMore/it/unibo/ctxWebGuiExecutor/webguiexecutor.pl", 
		"./srcMore/it/unibo/ctxWebGuiExecutor/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
