/* Generated by AN DISI Unibo */ 
package it.unibo.testmbotagent;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractTestmbotagent extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	//protected String mqttServer = "tcp://192.168.43.229:1883";
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractTestmbotagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/testmbotagent/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/testmbotagent/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doWork",doWork);
	    	stateTab.put("raiseSeries",raiseSeries);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "testmbotagent tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"testmbotagent STARTS\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://192.168.43.229:1883");
	    	//switchTo doWork
	        switchToPlanAsNextState(pr, myselfName, "testmbotagent_"+myselfName, 
	              "doWork",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doWork = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doWork",-1);
	    	String myselfName = "doWork";  
	    	parg = "assign(n,9)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonar(NAME,DISTANCE)","sonar(sonar1,10)", guardVars ).toString();
	    	emit( "sonarSensor", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "doWork";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonar(NAME,DISTANCE)","sonar(roversonar,20)", guardVars ).toString();
	    	emit( "sonarSensor", temporaryStr );
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "alarm(X)","alarm(fire)", guardVars ).toString();
	    	emit( "alarmev", temporaryStr );
	    	//switchTo raiseSeries
	        switchToPlanAsNextState(pr, myselfName, "testmbotagent_"+myselfName, 
	              "raiseSeries",false, false, null); 
	    }catch(Exception e_doWork){  
	    	 println( getName() + " plan=doWork WARNING:" + e_doWork.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doWork
	    
	    StateFun raiseSeries = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_raiseSeries",30);
	     pr.incNumIter(); 	
	    	String myselfName = "raiseSeries";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?inc(n,1,V)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonar(NAME,DISTANCE)","sonar(sonar2,V)", guardVars ).toString();
	    	emit( "sonarSensor", temporaryStr );
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?getVal(n,V)" )) != null ){
	    	temporaryStr = "emitted(sonar(sonar2,V))";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(50,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "raiseSeries";
	    	if( ! aar.getGoon() ) return ;
	    	repeatPlanNoTransition(pr,myselfName,"testmbotagent_"+myselfName,true,false);
	    }catch(Exception e_raiseSeries){  
	    	 println( getName() + " plan=raiseSeries WARNING:" + e_raiseSeries.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//raiseSeries
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
