/* Generated by AN DISI Unibo */ 
package it.unibo.blinker;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractBlinker extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractBlinker(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/blinker/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/blinker/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitCommand",waitCommand);
	    	stateTab.put("handleConsoleCmd",handleConsoleCmd);
	    	stateTab.put("startBlink",startBlink);
	    	stateTab.put("stopBlink",stopBlink);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "blinker tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"BLINKER starts...\"";
	    	println( temporaryStr );  
	    	//switchTo waitCommand
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "waitCommand",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitCommand = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitCommand",-1);
	    	String myselfName = "waitCommand";  
	    	//bbb
	     msgTransition( pr,myselfName,"blinker_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleConsoleCmd"), stateTab.get("startBlink"), stateTab.get("stopBlink") }, 
	          new String[]{"true","M","consoleCmdMsg", "true","M","startMsg", "true","M","stopMsg" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitCommand){  
	    	 println( getName() + " plan=waitCommand WARNING:" + e_waitCommand.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitCommand
	    
	    StateFun handleConsoleCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleConsoleCmd",-1);
	    	String myselfName = "handleConsoleCmd";  
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("consoleCmd(halt)");
	    	if( currentMessage != null && currentMessage.msgId().equals("consoleCmdMsg") && 
	    		pengine.unify(curT, Term.createTerm("consoleCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="halt(x)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("consoleCmd(X)"),  Term.createTerm("consoleCmd(halt)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("stopMsg",getNameNoCtrl(), QActorContext.dispatch, parg ); 
	    	}
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("consoleCmd(start)");
	    	if( currentMessage != null && currentMessage.msgId().equals("consoleCmdMsg") && 
	    		pengine.unify(curT, Term.createTerm("consoleCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="start(x)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("consoleCmd(X)"),  Term.createTerm("consoleCmd(start)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("startMsg",getNameNoCtrl(), QActorContext.dispatch, parg ); 
	    	}
	    	//switchTo waitCommand
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "waitCommand",false, false, null); 
	    }catch(Exception e_handleConsoleCmd){  
	    	 println( getName() + " plan=handleConsoleCmd WARNING:" + e_handleConsoleCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleConsoleCmd
	    
	    StateFun startBlink = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("startBlink",-1);
	    	String myselfName = "startBlink";  
	    	temporaryStr = "\"BLINKER start blinking\"";
	    	println( temporaryStr );  
	    	//switchTo waitCommand
	        switchToPlanAsNextState(pr, myselfName, "blinker_"+myselfName, 
	              "waitCommand",false, false, null); 
	    }catch(Exception e_startBlink){  
	    	 println( getName() + " plan=startBlink WARNING:" + e_startBlink.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//startBlink
	    
	    StateFun stopBlink = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("stopBlink",-1);
	    	String myselfName = "stopBlink";  
	    	temporaryStr = "\"BLINKER stop blinking\"";
	    	println( temporaryStr );  
	    	temporaryStr = "\"BLINKER ends...\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"blinker_"+myselfName,false,false);
	    }catch(Exception e_stopBlink){  
	    	 println( getName() + " plan=stopBlink WARNING:" + e_stopBlink.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//stopBlink
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
