/* Generated by AN DISI Unibo */ 
package it.unibo.usercmdmanager;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Usercmdmanager extends QActorMsgQueue{
	public MsgHandle_Usercmdmanager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
