/* Generated by AN DISI Unibo */ 
package it.unibo.applr1agent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Applr1agent extends QActorMsgQueue{
	public MsgHandle_Applr1agent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
