/* Generated by AN DISI Unibo */ 
package it.unibo.ledrasp;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractLedrasp extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractLedrasp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/ledrasp/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/ledrasp/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doBlinckAtStart",doBlinckAtStart);
	    	stateTab.put("waitForCommand",waitForCommand);
	    	stateTab.put("handleCmd",handleCmd);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "ledrasp tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "ledraspmqtt(started)";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://192.168.43.229:1883");
	    	//switchTo doBlinckAtStart
	        switchToPlanAsNextState(pr, myselfName, "ledrasp_"+myselfName, 
	              "doBlinckAtStart",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doBlinckAtStart = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("doBlinckAtStart",-1);
	    	String myselfName = "doBlinckAtStart";  
	    	customExecute("sudo bash led25GpioTurnOn.sh");
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(300,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "doBlinckAtStart";
	    	if( ! aar.getGoon() ) return ;
	    	customExecute("sudo bash led25GpioTurnOff.sh");
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(300,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "doBlinckAtStart";
	    	if( ! aar.getGoon() ) return ;
	    	customExecute("sudo bash led25GpioTurnOn.sh");
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(300,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "doBlinckAtStart";
	    	if( ! aar.getGoon() ) return ;
	    	customExecute("sudo bash led25GpioTurnOff.sh");
	    	//switchTo waitForCommand
	        switchToPlanAsNextState(pr, myselfName, "ledrasp_"+myselfName, 
	              "waitForCommand",false, false, null); 
	    }catch(Exception e_doBlinckAtStart){  
	    	 println( getName() + " plan=doBlinckAtStart WARNING:" + e_doBlinckAtStart.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doBlinckAtStart
	    
	    StateFun waitForCommand = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForCommand",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForCommand";  
	    	//bbb
	     msgTransition( pr,myselfName,"ledrasp_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleCmd") }, 
	          new String[]{"true","E","ctrlEvent" },
	          6000000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForCommand){  
	    	 println( getName() + " plan=waitForCommand WARNING:" + e_waitForCommand.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForCommand
	    
	    StateFun handleCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleCmd",-1);
	    	String myselfName = "handleCmd";  
	    	printCurrentEvent(false);
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ctrlEvent(leds,led1,on)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("ctrlEvent") && 
	    		pengine.unify(curT, Term.createTerm("ctrlEvent(CATEG,NAME,CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			customExecute("sudo bash led25GpioTurnOn.sh");
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ctrlEvent(leds,led1,off)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("ctrlEvent") && 
	    		pengine.unify(curT, Term.createTerm("ctrlEvent(CATEG,NAME,CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			customExecute("sudo bash led25GpioTurnOff.sh");
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"ledrasp_"+myselfName,false,true);
	    }catch(Exception e_handleCmd){  
	    	 println( getName() + " plan=handleCmd WARNING:" + e_handleCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleCmd
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
