/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrolm;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacontrolm extends QActorMsgQueue{
	public MsgHandle_Qacontrolm(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
