/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.player0;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Player0 extends AbstractPlayer0 { 
	public Player0(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
