/* Generated by AN DISI Unibo */ 
package it.unibo.presslogical;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Presslogical extends QActorMsgQueue{
	public MsgHandle_Presslogical(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
