/* Generated by AN DISI Unibo */ 
package it.unibo.ledhandler;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledhandler extends QActorMsgQueue{
	public MsgHandle_Ledhandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
