/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.player1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Player1 extends AbstractPlayer1 { 
	public Player1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
