/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.testeruser2;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Testeruser2 extends AbstractTesteruser2 { 
	public Testeruser2(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
