/* Generated by AN DISI Unibo */ 
package it.unibo.roveragent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Roveragent extends QActorMsgQueue{
	public MsgHandle_Roveragent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
