/* Generated by AN DISI Unibo */ 
package it.unibo.qaactuator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaactuator extends QActorMsgQueue{
	public MsgHandle_Qaactuator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
