/* Generated by AN DISI Unibo */ 
package it.unibo.orchestrator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Orchestrator extends QActorMsgQueue{
	public MsgHandle_Orchestrator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
