/* Generated by AN DISI Unibo */ 
package it.unibo.testmbotagent;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testmbotagent extends QActorMsgQueue{
	public MsgHandle_Testmbotagent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
