/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrol;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractQacontrol extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractQacontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/qacontrol/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/qacontrol/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForSensorEvent",waitForSensorEvent);
	    	stateTab.put("handleSensorEvent",handleSensorEvent);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "qacontrol tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "qacontrol(starts)";
	    	println( temporaryStr );  
	    	//switchTo waitForSensorEvent
	        switchToPlanAsNextState(pr, myselfName, "qacontrol_"+myselfName, 
	              "waitForSensorEvent",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForSensorEvent = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForSensorEvent",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForSensorEvent";  
	    	//bbb
	     msgTransition( pr,myselfName,"qacontrol_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleSensorEvent") }, 
	          new String[]{"true","E","sensorEvent" },
	          100000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForSensorEvent){  
	    	 println( getName() + " plan=waitForSensorEvent WARNING:" + e_waitForSensorEvent.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForSensorEvent
	    
	    StateFun handleSensorEvent = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSensorEvent",-1);
	    	String myselfName = "handleSensorEvent";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("sensorEvent(V)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("sensorEvent") && 
	    		pengine.unify(curT, Term.createTerm("sensorEvent(DATA)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg  ="curTemperatureValue(X)";
	    			String parg1 ="curTemperatureValue(V)";
	    			/* ReplaceRule */
	    			parg = updateVars(Term.createTerm("sensorEvent(DATA)"),  Term.createTerm("sensorEvent(V)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			parg1 = updateVars(Term.createTerm("sensorEvent(DATA)"),  Term.createTerm("sensorEvent(V)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg1);
	    			if( parg != null && parg1 != null  ) replaceRule(parg, parg1);	    		  					
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?evalTemperature(hot)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CMD)","ctrlEvent(on)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?evalTemperature(cold)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "ctrlEvent(CMD)","ctrlEvent(off)", guardVars ).toString();
	    	emit( "ctrlEvent", temporaryStr );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"qacontrol_"+myselfName,false,true);
	    }catch(Exception e_handleSensorEvent){  
	    	 println( getName() + " plan=handleSensorEvent WARNING:" + e_handleSensorEvent.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSensorEvent
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
