/* Generated by AN DISI Unibo */ 
package it.unibo.buttonimpl;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Buttonimpl extends QActorMsgQueue{
	public MsgHandle_Buttonimpl(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
