/* Generated by AN DISI Unibo */ 
package it.unibo.qarescuer;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qarescuer extends QActorMsgQueue{
	public MsgHandle_Qarescuer(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
