/* Generated by AN DISI Unibo */ 
package it.unibo.qa0;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractQa0 extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	//protected String mqttServer = "";
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractQa0(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/qa0/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/qa0/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("work",work);
	    	stateTab.put("handleInfo",handleInfo);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "qa0 tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	parg = "consult(\"curConfigTheory.pl\")";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//switchTo work
	        switchToPlanAsNextState(pr, myselfName, "qa0_"+myselfName, 
	              "work",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun work = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_work",0);
	     pr.incNumIter(); 	
	    	String myselfName = "work";  
	    	parg = "showSystemConfiguration";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	temporaryStr = "\"qa0 in ctxPivot READY\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"qa0_"+myselfName,false,
	          new StateFun[]{() -> {	//AD HOC state to execute an action and resumeLastPlan
	          try{
	            PlanRepeat pr1 = PlanRepeat.setUp("adhocstate",-1);
	            //ActionSwitch for a message or event
	             if( currentEvent.getMsg().startsWith("alarm") ){
	            	String parg = "alarm(X)";
	            	/* Print */
	            	parg =  updateVars( Term.createTerm("alarm(X)"), 
	            	                    Term.createTerm("alarm(X)"), 
	            		    		  	Term.createTerm(currentEvent.getMsg()), parg);
	            	if( parg != null ) println( parg );
	             }
	            repeatPlanNoTransition(pr1,"adhocstate","adhocstate",false,true);
	          }catch(Exception e ){  
	             println( getName() + " plan=work WARNING:" + e.getMessage() );
	             //QActorContext.terminateQActorSystem(this); 
	          }
	          },
	           stateTab.get("handleInfo") }, 
	          new String[]{"true","E","alarm", "true","M","info" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_work){  
	    	 println( getName() + " plan=work WARNING:" + e_work.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//work
	    
	    StateFun handleInfo = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleInfo",-1);
	    	String myselfName = "handleInfo";  
	    	printCurrentMessage(false);
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleInfo";
	    	if( ! aar.getGoon() ) return ;
	    	//onMsg 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("info(X)");
	    	if( currentMessage != null && currentMessage.msgId().equals("info") && 
	    		pengine.unify(curT, Term.createTerm("info(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="alarm(fire)";
	    		/* RaiseEvent */
	    		parg = updateVars(Term.createTerm("info(X)"),  Term.createTerm("info(X)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) emit( "alarm", parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"qa0_"+myselfName,false,true);
	    }catch(Exception e_handleInfo){  
	    	 println( getName() + " plan=handleInfo WARNING:" + e_handleInfo.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleInfo
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
