/* Generated by AN DISI Unibo */ 
package it.unibo.timedetector;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractTimedetector extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractTimedetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/timedetector/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/timedetector/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitCommand",waitCommand);
	    	stateTab.put("sendTimeKO",sendTimeKO);
	    	stateTab.put("end",end);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "timedetector tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"TIMEDETECTOR starts...\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(20000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	//switchTo waitCommand
	        switchToPlanAsNextState(pr, myselfName, "timedetector_"+myselfName, 
	              "waitCommand",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitCommand = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitCommand",-1);
	    	String myselfName = "waitCommand";  
	    	//bbb
	     msgTransition( pr,myselfName,"timedetector_"+myselfName,false,
	          new StateFun[]{stateTab.get("sendTimeKO") }, 
	          new String[]{"true","M","startTimeMsg" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitCommand){  
	    	 println( getName() + " plan=waitCommand WARNING:" + e_waitCommand.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitCommand
	    
	    StateFun sendTimeKO = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("sendTimeKO",-1);
	    	String myselfName = "sendTimeKO";  
	    	temporaryStr = "\"TIMEDETECTOR time is no more in range! Event!\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"timeState(X)","timeState(false)", guardVars ).toString();
	    	sendMsg("timeStateMsg","mvccontroller", QActorContext.dispatch, temporaryStr ); 
	    	//switchTo end
	        switchToPlanAsNextState(pr, myselfName, "timedetector_"+myselfName, 
	              "end",false, false, null); 
	    }catch(Exception e_sendTimeKO){  
	    	 println( getName() + " plan=sendTimeKO WARNING:" + e_sendTimeKO.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//sendTimeKO
	    
	    StateFun end = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("end",-1);
	    	String myselfName = "end";  
	    	temporaryStr = "\"TIMEDETECTOR ends...\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"timedetector_"+myselfName,false,false);
	    }catch(Exception e_end){  
	    	 println( getName() + " plan=end WARNING:" + e_end.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//end
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
