/* Generated by AN DISI Unibo */ 
package it.unibo.timedetector;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Timedetector extends QActorMsgQueue{
	public MsgHandle_Timedetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
