/* Generated by AN DISI Unibo */ 
package it.unibo.elabactor;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Elabactor extends QActorMsgQueue{
	public MsgHandle_Elabactor(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
