/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.applr1agent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Applr1agent extends AbstractApplr1agent { 
	public Applr1agent(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
