/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.frontendmanager1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Frontendmanager1 extends AbstractFrontendmanager1 { 
	public Frontendmanager1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
