/* Generated by AN DISI Unibo */ 
package it.unibo.qabuttonclient;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabuttonclient extends QActorMsgQueue{
	public MsgHandle_Qabuttonclient(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
