/* Generated by AN DISI Unibo */ 
package it.unibo.testsystem;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractTestsystem extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractTestsystem(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/testsystem/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/testsystem/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("dotest",dotest);
	    	stateTab.put("raiseSeries",raiseSeries);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "testsystem tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	parg = "assign(n,9)";
	    	//QActorUtils.solveGoal(myself,parg,pengine );  //sets currentActionResult		
	    	solveGoal( parg ); //sept2017
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "p(Distance,Angle)","p(60,0)", guardVars ).toString();
	    	emit( "polar", temporaryStr );
	    	temporaryStr = "\"testmbotagent STARTS\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"testsystem_"+myselfName,false,false);
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun dotest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("dotest",-1);
	    	String myselfName = "dotest";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(CMD)","usercmd(robotgui(w(low)))", guardVars ).toString();
	    	emit( "usercmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "dotest";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonar(SONAR,TARGET,DISTANCE)","sonar(sonar1,\"rover\",40)", guardVars ).toString();
	    	emit( "sonar", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "dotest";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(CMD)","usercmd(robotgui(w(low)))", guardVars ).toString();
	    	emit( "usercmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "dotest";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonar(SONAR,TARGET,DISTANCE)","sonar(sonar2,\"rover\",40)", guardVars ).toString();
	    	emit( "sonar", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "dotest";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "usercmd(CMD)","usercmd(robotgui(w(low)))", guardVars ).toString();
	    	emit( "usercmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "dotest";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonarDetect(X)","sonarDetect(roversonar)", guardVars ).toString();
	    	emit( "sonarDetect", temporaryStr );
	    	repeatPlanNoTransition(pr,myselfName,"testsystem_"+myselfName,false,false);
	    }catch(Exception e_dotest){  
	    	 println( getName() + " plan=dotest WARNING:" + e_dotest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//dotest
	    
	    StateFun raiseSeries = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_raiseSeries",30);
	     pr.incNumIter(); 	
	    	String myselfName = "raiseSeries";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?inc(n,2,V)" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "sonar(SONAR,TARGET,DISTANCE)","sonar(sonar2,\"rover\",V)", guardVars ).toString();
	    	emit( "sonar", temporaryStr );
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?getVal(n,V)" )) != null ){
	    	temporaryStr = "emitted(sonar(sonar2,V))";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(50,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "raiseSeries";
	    	if( ! aar.getGoon() ) return ;
	    	repeatPlanNoTransition(pr,myselfName,"testsystem_"+myselfName,true,false);
	    }catch(Exception e_raiseSeries){  
	    	 println( getName() + " plan=raiseSeries WARNING:" + e_raiseSeries.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//raiseSeries
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
