/* Generated by AN DISI Unibo */ 
package it.unibo.testsystem;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Testsystem extends QActorMsgQueue{
	public MsgHandle_Testsystem(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
